### ISSUE TITLE
Memcached Dependency

### ISSUE THREAD

**Issue by hanse** [webkom/passport-abakus#5]
The library should probably not depend on Memcached. That is, we should let it be up to the developer to decide how he or she wants to cache the user credentials.

Of course, one could just reimplement (serialize|deserialize)User, but you still have to pull down memjs from the registry, and you'd most likely get an error due to memcached not being installed when trying to initialize the client.

**Comment by relekang** [comment]
I agree, we should probably remove `serializeAbakusUser` and `deserializeAbakusUser` since they do not have anything abakus spesific.
